### ISSUE TITLE
getConnection timeout

### ISSUE THREAD

**Issue by philrykoff** [vert-x3/vertx-mysql-postgresql-client#24]
Maybe this is still the non-async inner me, but it would be great to have some kind of error handling / logging in cases when there can no free connection object be returned from the pool after a given amount of time.

Or is this not possible in async world?

Thanks a lot for this great lib!

```
        this.corePostgreSqlClient.getConnection(res -> {
            
            if (res.succeeded())
            {
                future.complete(res.result());
                ctx.runOnContext(v -> future.setHandler(handler));
            }
            else 
            {
                // handle error cases, e.g. timeouts
                future.fail(res.cause());
                ctx.runOnContext(v -> future.setHandler(handler));
            }
        });
```

**Comment by cescoffier** [comment]
It should work no ?

When a connection cannot be retrieved from the pool, a failure is passed to the connection handler:

https://github.com/vert-x3/vertx-mysql-postgresql-client/blob/master/src/main/java/io/vertx/ext/asyncsql/impl/BaseSQLClient.java#L67

**Comment by Narigo** [comment]
Just a wild guess, but shouldn't you set the handler for the future before completing it with `future.complete(XXX)` or `future.fail(XXX)` ?

**Comment by philrykoff** [comment]
Interesting finding... will check it in comparable source code :)

**Comment by philrykoff** [comment]
At least in the vert.x source code, there are examples for both variations. There are also examples for using ctx.runOnContext(...) and not using it.

Are there any suggestions on the right way(TM)?

**Comment by Narigo** [comment]
@philrykoff sorry, I missed the notification.

When you get in the handler of `getConnection`, it should run on the same thread where you started it. When you do a `runOnContext`, it will do, whatever you put in that handler, asynchronously on the same thread where you got the Context (`ctx`) from.

So in your specific use case, it will tell `future` to complete with a result and then commands Vert.x to do whatever else it may want to do (like calling the not yet set handler of `future`) before setting the handler for the future.

I'd uncomment (1), but I think you could also use variant (2):

```
// (1) future.setHandler(handler);
this.corePostgreSqlClient.getConnection(res -> {
  // (2) future.setHandler(handler);
  if (res.succeeded()) {
    future.complete(res.result());
  } else {
    // handle error cases, e.g. timeouts
    future.fail(res.cause());
  }
});
```

Please reopen, if there is still an issue with not getting a failure for your handler - otherwise I hope this code helps you :)

**Comment by philrykoff** [comment]
Thanks a lot, @Narigo ! :-)
