### ISSUE TITLE
Missing vertx 3.1.0  client

### ISSUE THREAD

**Issue by reistiago** [vert-x3/vertx-mysql-postgresql-client#26]
Can't find a build for vertx 3.1.0

**Comment by cescoffier** [comment]
The vertx-mysql-postgresql-client project is not part of the official vert.x stack, that's why it was not released with the other components. Several issues have motivated this choice. For instance, the vertx-mysql-postgresql-client uses a scala library that does not allow us to be a drop-in replacement for the vertx-jdbc-client. So, I would recommend you to use the vertx-jdbc-client (http://vertx.io/docs/vertx-jdbc-client/java/)

**Comment by reistiago** [comment]
I understand that this client doesn't belong to the official stack, but it
was possible to use it with vertx 3.0.0 using the latest milestone.
Currently it's not possible to use it with vertx 3.1.0, is a compatible
version expected or are you really only targeting 3.2.x ?

Thanks

**Comment by cescoffier** [comment]
you mean using 3.0.0-milestone6 ? Because the client was not released with the 3.0.0 (no classifier) as it had concurrency issues.

**Comment by reistiago** [comment]
Yep, I was using the milestone. Will change back to the jdbc driver then.
Thanks.
