### ISSUE TITLE
ConnectionStillRunningQueryException - Connection Pool

### ISSUE THREAD

**Issue by leosilvadev** [vert-x3/vertx-mysql-postgresql-client#64]
Hey guys, I am facing this exception, I got the reason for that but:
- does vertx-mysql-postgresql-client apply any connection pool for the driver, or should I do it by myself?
- if it does not, any suggestion?

I am asking because if we use it, this error should not be happening, since we should never get an 'active/in-usage' connection from the pool

Thanks!

**Comment by leosilvadev** [comment]
So, well, checking the code I realized that we have it, so I should not face this exception, right?
Want some code to check the error?

**Comment by pmlopes** [comment]
@leosilvadev you will get that error in a situation where you issue a new query without waiting for the previous one to complete, here is an example:
```java
for (int i = 0; i < 100; i++) {
  conn.execute("insert into table X values (1, 2, 3)", res -> {});
}
```

In order to make this work one needs to wait for the current query to return:

```java
new Handler<Integer>() {
  @Override
  public void handle(Integer idx) {
    if (idx == 100) {
      // stop condition
    } else {
      final Handler<Integer> self = this;
      conn.execute("insert into table X values (1, 2, 3)", res -> {
       if (res.failed()) {
         // probably roll back...
       } else {
         self.handle(idx + 1);
       }
      });
    }
  }
}.handle(0);
```

There are many other ways to do this too... the important thing here is that you wait for the response before issuing a new query.

**Comment by leosilvadev** [comment]
@pmlopes yeah, in fact I am doing that already, I still have to debug more to see why exactly we are facing this. As soon as I got any new I post here.
